//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace H_AsistenciaPosgrado.Conexion
{
    using System;
    
    public partial class Sp_MatriculaConsultar_Result1
    {
        public int Id_Matricula { get; set; }
        public System.DateTime FechaRegistroMatricula { get; set; }
        public int Id_ConfiguracionCohorte { get; set; }
        public bool Matricula_Vigente { get; set; }
        public int Id_TipoMatricula { get; set; }
        public string DescripcionTipoMatricula { get; set; }
        public bool EliminadoTipoMatricula { get; set; }
        public int IdentificadorTipoMatricula { get; set; }
        public int Id_preseleccionado { get; set; }
        public Nullable<decimal> PuntajePreseleccionado { get; set; }
        public Nullable<bool> EliminadoPreseleccionado { get; set; }
        public int IdInscripcion { get; set; }
        public Nullable<int> IdPeriodo { get; set; }
        public int IdPersona { get; set; }
        public string Nombres { get; set; }
        public string SegundoNombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Cedula { get; set; }
        public string Email { get; set; }
        public string EmailInstitucional { get; set; }
        public string TelefonoC { get; set; }
        public string TelefonoD { get; set; }
    }
}
